### PR TITLE
Create Team 622 Inferno

### PR DESCRIPTION
**Pull request by hanson-lam**

### CODE REVIEW

**Comment by robobenklein** [comment]
@lproctor10242 is waiting for #45

**Review by ParkerNC — APPROVED** [review]

**Comment by robobenklein** [comment]
All that's left is for members to review this PR and add some details about your choice of project! (You can narrow it down later, we just want a general idea to start.)

**Review by lproctor10242 — APPROVED** [review]

**Review by IanMacDougall — APPROVED** [review]

**Comment by robobenklein** [comment]
What is your project? I can't really tell from that description tbh...

**Comment by hanson-lam** [comment]
Let me update it lol

**Comment by robobenklein** [comment]
Looks like you committed a merge conflict, be sure to clean those up before you commit! If you notice it before you push, I recommend amending, but after pushing it's probably better to avoid a force push and just make a new commit to fix it.

**Comment by hanson-lam** [comment]
How would I go about fixing the conflict?

**Comment by robobenklein** [comment]
Just edit the file to get rid of the merge conflict markers and commit/push the new version.

**Review by AZHenley — APPROVED** [review]

**Comment by AZHenley** [comment]
Spoke to them Thursday about this project. Sounds good to me.

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
