### PR TITLE
added the inital version of our poggies team

### PR DESCRIPTION
**Pull request by SKBlank**

### CODE REVIEW

**Review by bepri — APPROVED** [review]
Cool and good

**Review by bradymclaugh — APPROVED** [review]
Seems good to me

**Review by e-vananderson — APPROVED** [review]

**Comment by robobenklein** [comment]
Reminder to choose or propose a project!

**Comment by robobenklein** [comment]
@SKBlank reminder to accept the org invite! Otherwise you'll never get access to your team's repo.

**Review by robobenklein — CHANGES_REQUESTED** [review]
Re-request my review when you've got a project idea settled on.

**Review by e-vananderson — APPROVED** [review]

**Comment by e-vananderson** [comment]
### Issues (since they're due tonight and we don't have a repo yet)

#### weather api (ipelton):

- accept location input from game framework
- retrieve 7 day forecast
- format 7 day forecast for easy pyqt implementation

#### map api (eander68):

- get map of specified range (whatever part of the world we decide to do)
- display marker and coords on click event
- pass selected location to game framework

#### gui (sblank11):

- start button
- select button for map
- display current score
- design interface displaying map and forecast side by side

#### game framework (bmclaug6):

- generate random location on start button click
- pass generated location to weather api
- accept location input from map api
- implement algorithm for score calculation

**Comment by robobenklein** [comment]
Note: issues are due by *class time* thursday, not tonight.

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
