### PR TITLE
Create jananth2.md

### PR DESCRIPTION
**Pull request by jananth2**

### CODE REVIEW

**Comment by robobenklein** [comment]
It appears you made your commit on GitHub, not in your local environment!

Before this is merged, can you confirm that your local environment is properly set up? (If you don't have your local dev setup using the correct github commit author, you won't get any credit for those commits!)

**Comment by jananth2** [comment]
Sorry about that. Hopefully should be good now!

**Comment by robobenklein** [comment]
It looks like your latest commit still isn't authored correctly. Remember to set the git config email with an address verified on your github account.

**Comment by jananth2** [comment]
Sorry about that. Forgot to change that. I believe it should work now.

**Pull request merged**
