### PR TITLE
Create mwalte21.md

### PR DESCRIPTION
**Pull request by MatthewWalters1**
added my student file

### CODE REVIEW

**Comment by robobenklein** [comment]
It appears you made your commit on GitHub, not in your local environment!

Before I merge this, can you confirm that your local environment is properly set up? (If you don't have your local dev setup using the correct github commit author, you won't get any credit for those commits!)

**Comment by MatthewWalters1** [comment]
As far as I know, I have everything set up, and I cloned the repo to my
computer, but when I try to push from it it says I don't have the correct
access rights, what can I do to change that?

**Comment by robobenklein** [comment]
Make sure you're cloning your fork of the repo, and not this repo itself.

**Comment by MatthewWalters1** [comment]
No sir, I'm cloning my fork, I deleted and cloned it again, and its still
not working

**Comment by MatthewWalters1** [comment]
Sorry, never mind, my computer had 2 ssh keys and was defaulting to the
wrong one, now it pushed properly

**Pull request merged**
