### PR TITLE
Create spate118.md

### PR DESCRIPTION
**Pull request by spate118**

### CODE REVIEW

**Comment by robobenklein** [comment]
Awesome, content looks good, but just to verify, you do have your account connected locally on your machine right? Part of this process is to ensure that everyone has git installed and functioning locally where they can run their pyqt project.

**Comment by spate118** [comment]
How can I test if I have it connected locally? I remember doing it but not sure if I did it correctly.

**Comment by robobenklein** [comment]
If you have everything set up correctly locally you should be able to clone your fork of this repo using the git command. (I'll be showing this in class today)

**Comment by robobenklein** [comment]
If you know your local dev setup is good to go, tell me and I'll merge this, otherwise just ask for help!

**Comment by spate118** [comment]
I have set up everything correctly locally.

**Pull request merged**
