### PR TITLE
Added team NobleToads to team list

### PR DESCRIPTION
**Pull request by Thalomir**

### CODE REVIEW

**Comment by robobenklein** [comment]
Got any project ideas in mind? Or are you just going to choose one of the examples?

**Comment by robobenklein** [comment]
Reminder to choose or propose a project, we just need something so that you can start the iteration this thursday with a goal in mind.

**Comment by robobenklein** [comment]
@Thalomir reminder to accept the org invite! Otherwise you won't be able to access your team's repo.

**Comment by Thalomir** [comment]
> @Thalomir reminder to accept the org invite! Otherwise you won't be able to access your team's repo.

I have accepted my invite. Also, our idea for our application was an idle game similar to a cookie clicker that utilized a weather API in order to change how the game functioned based on the real-life weather where you live. We will also use Twitter API to give the users the option to tweet about their success and achievements in-game in order to generate hype for the idle game.

**Comment by robobenklein** [comment]
Sounds cool to me, put that description into the file and I'll merge it

**Review by robobenklein — CHANGES_REQUESTED** [review]
Re-request my review once you've put the project proposal in the file.

**Review by lukepmccombs — APPROVED** [review]

**Comment by Thalomir** [comment]
We have fixed our file and are ready for a re-review.

**Comment by argvrutter** [comment]
Looks good to me. I like the idea of varying performance based on weather API

**Review by robobenklein — APPROVED** [review]
I will play dis game

**Review by Benjamin-Schwartz — COMMENTED** [review]
I approve

**Review by Kmac0103 — COMMENTED** [review]
I approve the changes

**Comment by robobenklein** [comment]
You know there's an actual "approve" button right? When you submit a review, you can either approve or request changes via a radio selection.

**Review by yahmad1-vols — COMMENTED** [review]
Looks mostly good to me, I added another PR with grammar and spelling fixes.

**Pull request merged**
