### PR TITLE
Added my student file

### PR DESCRIPTION
**Pull request by bowlingparker**

### CODE REVIEW

**Comment by argvrutter** [comment]
You will need to set your email address via git config to match your email on file with GitHub. This will associate commits frmo you with your GitHub account. 
See [https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git)

**Comment by robobenklein** [comment]
You should submit your Team PR separately so that it can be reviewed after you're invited to the organization.

**Comment by bowlingparker** [comment]
Where should this be submitted to instead?

**Comment by robobenklein** [comment]
A good example of the separate team PR is https://github.com/utk-cs/CS340-Fall-2021/pull/100

**Comment by bowlingparker** [comment]
Do I add the file into the teams folder of the main branch?

**Comment by robobenklein** [comment]
You should either use your fork of this repo or a separate branch on this repo (once this PR is merged) to make a PR for your team.

If you are submitting multiple PRs with different changes from your same forked repo, you'll need to use branches which were covered in the in-class demo. (If you don't know how - just ask!)

**Comment by bowlingparker** [comment]
Okay thanks. Has my PR been merged yet?

**Comment by robobenklein** [comment]
Nope, you should look on GitHub (which is where this discussion is actually happening) to see the status of your work. If this PR were already merged it would say so instead of "Open".

**Comment by bowlingparker** [comment]
what can I do to fix it? I thought I updated the email address

**Comment by robobenklein** [comment]
The easiest option would probably be to open a new PR for your student file, get it merged, then after that open a PR for your team file.

**Comment by bowlingparker** [comment]
Okay, and how exactly do I do that? is a PR just forking the original repo that the instructions said to do?

**Comment by robobenklein** [comment]
Were you there for class? I think you might have a misunderstanding about how to use git which I think could be much better explained showing it in person. (Or we could hop in a video call to screen share later in the days)

A fork of a repo is basically a copy made on github. A PR is a request to merge changes from a branch (on either repo) into another.

To make a new PR you should create a new branch on your fork that includes the commits with the desired changes. Then when opening the PR you'd select that correct branch to merge from, into the destination which is the `main` branch on this repo.

**Comment by bowlingparker** [comment]
Got it. I'll try that. I was there for class and paid attention. It's hard to remember all the different operations to get a branch set up.

**Pull request merged**
