### PR TITLE
adding a team file, but we only have 2 people so far

### PR DESCRIPTION
**Pull request by MatthewWalters1**
adding a team file, but we only have 2 people

### CODE REVIEW

**Comment by robobenklein** [comment]
@jacobgpagee needs to accept the org invite

**Comment by robobenklein** [comment]
Going to start assigning people without a team randomly, would you like to add 2 or 3 more people to this team? (Or if you have anyone in mind who doesn't have a team yet as shown in students.yml ping them today and ask.)

**Comment by MatthewWalters1** [comment]
Probably just 2 more, but I dont know anyone in particular

**Comment by robobenklein** [comment]
Make sure you update the file with the new members!

**Review by robobenklein — APPROVED** [review]
I will approve this but you must keep in mind that this "online leaderboard" must be accessible to us and/or the code for it should be included in your project with instructions on how to run / connect.

**Pull request merged**
