### PR TITLE
Teamok.md

### PR DESCRIPTION
**Pull request by Franklin-Xie**

### CODE REVIEW

**Comment by robobenklein** [comment]
Going to start assigning people without a team randomly, would you like to add 2 or 3 more people to this team? (Or if you have anyone in mind who doesn't have a team yet as shown in students.yml ping them today and ask.)

**Comment by robobenklein** [comment]
Your file needs to be markdown (.md)

**Comment by argvrutter** [comment]
Assigning new team members

**Comment by argvrutter** [comment]
@oselyuti @LohithGangula @AndersonWalsh you've been assigned to this team.

**Review by robobenklein — CHANGES_REQUESTED** [review]
Make the file a markdown file (`.md`) and add all the members to it.

**Review by oselyuti — APPROVED** [review]
Looks good!

**Review by Franklin-Xie — COMMENTED** [review]
Ok

**Review by leoked — COMMENTED** [review]
Ok

**Review by robobenklein — CHANGES_REQUESTED** [review]
Settled on a project yet? (re-request my review when you have)

**Review by LohithGangula — APPROVED** [review]

**Comment by LohithGangula** [comment]
> Settled on a project yet? (re-request my review when you have)

im fine with either the note-taking or weather app. up to everyone else

**Comment by oselyuti** [comment]
I am also fine with either but I would prefer the weather app.

**Comment by AndersonWalsh** [comment]
I think either the note taking app or the weather app would be fine too, with a slight preference towards the weather app. Is there any further action we need to take as a team on our markdown file? Are we "team ok"?

**Review by AndersonWalsh — APPROVED** [review]

**Comment by robobenklein** [comment]
You should include your project decision in your file.

**Review by AndersonWalsh — APPROVED** [review]
We've finalized our project decision.

**Review by oselyuti — APPROVED** [review]

**Review by LohithGangula — APPROVED** [review]
includes all names and project. looks good

**Comment by AndersonWalsh** [comment]
We've mapped out issues and assigned them in this live document, since we don't have a repo yet: https://docs.google.com/document/d/1WqjLZw3QF2p5Xb82qMRSHrwFon2_D4JGsOau8IL17TE/

**Comment by robobenklein** [comment]
> We've mapped out issues and assigned them in this live document, since we don't have a repo yet: https://docs.google.com/document/d/1WqjLZw3QF2p5Xb82qMRSHrwFon2_D4JGsOau8IL17TE/

Remember, Issues are due by *class time*, not tonight. Your team PR is also required to be merged by class time, which is how your team's repo will be created.

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
