### PR TITLE
Team Alabio

### PR DESCRIPTION
**Pull request by robobenklein**
This is a PR for a randomly selected team, you all are required to pull the branch it's on, add your team file matching the name of this branch (`alabio.md`) and fill it with your member list and project choice.

### CODE REVIEW

**Comment by jrduell** [comment]
Hey y'all want to drop your emails or something in here? I created the alabio.md file and entered my name. I guess we all need to do that and talk about project ideas

**Comment by Crestor123** [comment]
My email's cmoore99@vols.utk.edu
I thought it might be fun to make the text editor, but to spin it for book writing; maybe have tools such that you can organize a particular document as a scene, character, location, etc. and then graphically present these in some way so that related elements are together.  I'm up for whatever project everyone wants to do, though.

**Comment by pattle-vols** [comment]
My email is: pattle@vols.utk.edu

I like Crestor's idea of a book organizer text editor.

**Comment by Notatoe** [comment]
my email is nmorri11@vols.utk.edu
I personally have no strong opinions towards a project idea so I would also be good with Chris' idea

**Comment by jrduell** [comment]
Ok I made a teams group if y'all want to check. Lmk if there's any trouble getting on.

**Comment by Notatoe** [comment]
I tried looking, but I don't know where to find the alabio.md file. I'm probably just being dumb and looking in all of the wrong spots.
Also do you all wanna make a group on groupme or discord so that communication can be faster?

**Comment by pattle-vols** [comment]
Want to try this?
https://discord.gg/k2bqPRUP

**Comment by robobenklein** [comment]
> I tried looking, but I don't know where to find the alabio.md file. I'm probably just being dumb and looking in all of the wrong spots.

Your file does not exist yet, your task was to create it, just as 21 other teams have already done.

I've already created a branch for you to commit to (`team/alabio`) which you should check out, commit the file to, and push it.

**Comment by argvrutter** [comment]
Looks good to me. Assuming all team members have reviewed & approve of the proposal, I'm ready to merge this in.

**Review by Crestor123 — APPROVED** [review]

**Pull request merged**
