### PR TITLE
Create kwooda13.md

### PR DESCRIPTION
**Pull request by kwooda13**
first time!

### CODE REVIEW

**Comment by robobenklein** [comment]
It appears you made your commit on GitHub, not in your local environment!

Before I merge this, can you confirm that your local environment is properly set up? (If you don't have your local dev setup using the correct github commit author, you won't get any credit for those commits!)

**Comment by kwooda13** [comment]
I think so. I have the CS 340 files
on my machine that I got through GitHub... How do I check if I’m using the
correct commit author?

My apologies…

**Comment by robobenklein** [comment]
You can check if your commit author email is correct by pushing a commit to github from your machine, which is why we showed the demo in class doing all the changes on our local machine.

**Comment by kwooda13** [comment]
Alright I pushed a commit. It told me “the branch is up to date, nothing to
commit…” Thank you for you patience.

**Comment by kwooda13** [comment]
Okay I’ve been messing with it a lot on my local machine; it should work
now. My bad for being lost…

**Comment by robobenklein** [comment]
Alright, I can merge this now, but just remember we'll only grade commits that have their github account properly linked to the commit!

**Comment by robobenklein** [comment]
Wait, nvm, your file doesn't look right, oops

**Comment by kwooda13** [comment]
Oh crap. Is my GitHub username wrong?

**Comment by robobenklein** [comment]
Check that your markdown file follows the right format, it needs to have your name, netid, and github username.

**Comment by kwooda13** [comment]
Does this look okay?

**Comment by robobenklein** [comment]
My apologies, I messed up merging this one, so I created a new PR for you at https://github.com/utk-cs/CS340-Fall-2021/pull/107 or you are free to open a new one with the correct changes.

**Comment by kwooda13** [comment]
Okay. So does that mean we are good to go?

**Comment by robobenklein** [comment]
No, you still need to finish filling out the format, your current commit doesn't include any information in the markdown file itself.

**Pull request merged**
