### PR TITLE
Add team notveryqt

### PR DESCRIPTION
**Pull request by jallbrit**

### CODE REVIEW

**Review by dominicmkennedy — APPROVED** [review]

**Review by jacob-armiger — APPROVED** [review]
Great work!

**Review by jacob-armiger — APPROVED** [review]

**Comment by robobenklein** [comment]
Some additional project details would be great so we can tell whether or not you'll be on target with it

**Review by ljakstas — APPROVED** [review]

**Review by AZHenley — APPROVED** [review]
Will this make me rich?

**Review by robobenklein — APPROVED** [review]
if this doesn't make me rich, -1e-9 points to final grade

**Pull request merged**
