### PR TITLE
Add Team Alpha

### PR DESCRIPTION
**Pull request by anphan7**
add new team

### CODE REVIEW

**Comment by robobenklein** [comment]
@sjohn248 @taha59 @dwhite75 need their personal PRs merged & an invite in order to get assigned to this team

**Review by sjohn248 — APPROVED** [review]
Looks good!

**Comment by anphan7** [comment]
@robobenklein  can you add dwhite75 for review? thank you

**Comment by taha59** [comment]
i approve

**Review by taha59 — APPROVED** [review]

**Comment by robobenklein** [comment]
no, because @dwhite75 hasn't accepted the org invite

**Comment by anphan7** [comment]
@robobenklein now he did, can you check again?

**Review by robobenklein — APPROVED** [review]

**Review by dwhite75 — COMMENTED** [review]
add to team

**Review by dwhite75 — APPROVED** [review]

**Pull request merged**
