### PR TITLE
Added Team HappyLittleTrees looking-for-members

### PR DESCRIPTION
**Pull request by Bdallstr**

### CODE REVIEW

**Comment by robobenklein** [comment]
Going to start assigning people without a team randomly, would you like to add 2 or 3 more people to this team? (Or if you have anyone in mind who doesn't have a team yet as shown in students.yml ping them today and ask.)

**Comment by argvrutter** [comment]
Inviting Devin Munsey, dmunsey4, gh: Dev5ter pending their acceptance.

**Comment by robobenklein** [comment]
@Dev5ter needs to accept the org invite, @RCSIII @grant-webb1 have been assigned

**Review by EmeraldHarbor — APPROVED** [review]

**Comment by robobenklein** [comment]
Make sure you add all the new names to the team's file.

**Review by robobenklein — CHANGES_REQUESTED** [review]
Awaiting new members to be added to the file.

**Comment by Bdallstr** [comment]
The information should be up to date with the list of assignees.

**Review by RCSIII — APPROVED** [review]

**Review by grant-webb1 — APPROVED** [review]

**Review by robobenklein — CHANGES_REQUESTED** [review]
one more to add to the file please, re-request my review when @Dev5ter is in

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
