### PR TITLE
Create ssuresh6.md

### PR DESCRIPTION
**Pull request by suhilsuresh**

### CODE REVIEW

**Comment by robobenklein** [comment]
Your commit signature indicates you did not make these changes via your git client. We are asking that students use their git client (ie shell commands) for this assignment

Follow these steps to properly configure your git config: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git

After doing that, create an empty commit via your local terminal (ie, `git commit --allow-empty "Your message here"`) and push the changes so that we can see you have properly set up your git client. Furthermore, we strongly encourage use of your local client for future commits.

**Comment by argvrutter** [comment]
Delete the file duplicate file outside of students/ dir please.

**Comment by suhilsuresh** [comment]
It’s deleted. Sorry about that.

**Comment by suhilsuresh** [comment]
I’m confused. I created a new pull request and did what was asked in the
previous email. Did I miss something?

**Pull request merged**
