### PR TITLE
team and project proposal for team `Team-v2FINAL1`

### PR DESCRIPTION
**Pull request by reedsemmel**
This project might involve an extra server which needs to be approved by Henley according to the README, so I will ping him @AZHenley . 

The server component would just be an http api server, also written in python. All it would do is tell each client what the moves are. No need for a database or anything. It can be completely done in memory. We can distribute the server as a docker image on ghcr.io as well.

### CODE REVIEW

**Review by 1480c1 — APPROVED** [review]

**Comment by robobenklein** [comment]
I would be fine with a docker dependency personally so long as all code to build the image locally is included in the repo as well. (A compose file would be preferred as well)

**Comment by robobenklein** [comment]
@M9909-AB You've been invited, reminder to accept!

**Review by M9909-AB — APPROVED** [review]

**Review by AZHenley — APPROVED** [review]
I recommend not worrying about adding the server until later on. Make single player chess work first.

**Comment by reedsemmel** [comment]
Looks like its all good to go, should I finalize the merge or is that up to a TA/Henley?

**Comment by robobenklein** [comment]
Well I don't see anything left, so LGTM!

**Comment by robobenklein** [comment]
I created your team's repo, you're ready to go!

**Comment by 1480c1** [comment]
I have realized that reed has messed up, we are missing a hyphen, is this fine or should this be remedied?

image

**Comment by robobenklein** [comment]
I plan on using the filename for the team as part of gradescripts and the repo name on github, since you're all part of this repo now you can open a new PR on another branch to change it if you want.

**Pull request merged**
