### PR TITLE
team added

### PR DESCRIPTION
**Pull request by kwooda13**

### CODE REVIEW

**Review by ciadonisi — APPROVED** [review]

**Review by jnotowich — APPROVED** [review]

**Comment by robobenklein** [comment]
Reminder to choose or propose a project!

**Review by robobenklein — CHANGES_REQUESTED** [review]
Add your choice of project to your file!

**Comment by ciadonisi** [comment]
where do we put the project descriptions? What file?

**Review by ciadonisi — APPROVED** [review]

**Review by ciadonisi — APPROVED** [review]

**Review by AZHenley — CHANGES_REQUESTED** [review]
Can you expand on what you mean by sportsbook/daily fantasy sports project? What major features do you want to provide and what is an example scenario of using the application?

**Review by AZHenley — APPROVED** [review]

**Review by AZHenley — CHANGES_REQUESTED** [review]
(See previous comment, mistakenly marked this as Approved.)

**Review by jnotowich — APPROVED** [review]

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
