### PR TITLE
Create kwooda13.md

### PR DESCRIPTION
**Pull request by robobenklein**
Reopening due to my accidental merge. @kwooda13 go ahead and push your fixing commits to the same branch.

### CODE REVIEW

**Comment by kwooda13** [comment]
Okay so I deleted my markdown file and created it with the format...
Full Name: Kenneth Woodard
netID: kwooda13
GitHub Username: kwooda13

I then used git add, commit, and push. I thought that this was all we needed in our MD file?

**Comment by robobenklein** [comment]
Yeah, if you pushed it to some other branch open a PR from that branch into this repo's main branch.

**Comment by kwooda13** [comment]
Okay so when I made my pull request this time the file looked good. Hopefully I didn't screw it up again.

**Comment by kwooda13** [comment]
It's #109 just FYI.

**Pull request closed without merging**
