### PR TITLE
Adding Team Mark Down

### PR DESCRIPTION
**Pull request by mrchausgit**

### CODE REVIEW

**Comment by robdgrif** [comment]
I am a member

**Comment by AlexanderKrneta** [comment]
I am a member

**Comment by robobenklein** [comment]
@ndrake127 needs to accept the org invite

**Comment by robobenklein** [comment]
If @ndrake127 isn't assigned in a few hours, they will not be part of this team.

**Comment by robobenklein** [comment]
Also in order for your team repo to be created you need to make sure everyone has accepted the org invite.

**Comment by ndrake127** [comment]
Does everything look correct, now? @robobenklein

**Comment by AZHenley** [comment]
I'm not really sure what a Minimalist Schedule Calender/Generator is. Can you expand on what the major features will be and an example scenario of how a user would use it?

**Review by AZHenley — CHANGES_REQUESTED** [review]
I'm not really sure what a Minimalist Schedule Calender/Generator is. Can you expand on what the major features will be and an example scenario of how a user would use it?

**Review by robobenklein — CHANGES_REQUESTED** [review]
need more information about what a schedule generator does

**Review by ndrake127 — COMMENTED** [review]
I created another pull request [(175)](https://github.com/utk-cs/CS340-Fall-2021/pull/175) with more proposal description

**Comment by ndrake127** [comment]
Sorry for the confusion, I think we were all a bit confused about the process of getting the team set up. Once we get this issue resolved we should be fine to continue with the project.

**Pull request closed without merging**
