### PR TITLE
Adding Team Dragon

### PR DESCRIPTION
**Pull request by tlplayer**
This is my team and we are going to make a weather app.

### CODE REVIEW

**Comment by robobenklein** [comment]
@tfowler6 @elidberb need to accept the org invitation!

**Review by tfowler6 — APPROVED** [review]
looks good 👍🏻

**Review by tfowler6 — APPROVED** [review]
👍🏻

**Review by kpatel68 — APPROVED** [review]
noice

**Review by elidberb — APPROVED** [review]
All of the information looks correct!

**Comment by tlplayer** [comment]
@robobenklein would you please approve the pr?

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
