### PR TITLE
created alabio.md

### PR DESCRIPTION
**Pull request by jrduell**

### CODE REVIEW

**Comment by robobenklein** [comment]
(p.s. use the script `python scripts/teams.py` to populate the teams.yml if you aren't using it already, but no need to since I'll run it myself anyways)

**Comment by robobenklein** [comment]
Also, any reason this isn't on the existing PR I made for the team?

**Comment by jrduell** [comment]
I'm not sure. I had covid when we went over the script stuff and the zoom recording didn't work.

**Comment by robobenklein** [comment]
Steps to use the branch I created for you on this repo: (#167)

1. clone this repo (or set your local repo's `origin` remote url to this one and git fetch)
2. checkout / switch to the branch I made for your team
3. commit your file to that branch
4. push it

**Pull request closed without merging**
