### PR TITLE
added team_001.md

### PR DESCRIPTION
**Pull request by DBeatyPreston**

### CODE REVIEW

**Comment by robobenklein** [comment]
@joshuakwright needs their student PR done before they can get added to this team!

**Comment by DBeatyPreston** [comment]
i checked and was able to see his .md in the students folder. is there anything else that needs to be done?

**Comment by robobenklein** [comment]
Looks like he hasn't accepted the org invite yet, once he does, assign him to this PR.

**Comment by robobenklein** [comment]
Also, sometime this weekend we'll be creating your project repos, so if you have any project ideas in mind or which example you'd like to use, go ahead and add that to your team file so we have some idea of what you'll be working on!

**Comment by joshuakwright** [comment]
how do I accept the org invite?

**Comment by robobenklein** [comment]
You should have received an email, if not, look at https://github.com/utk-cs and you should see an accept button.

**Comment by joshuakwright** [comment]
ok I accepted the invite

**Review by joshuakwright — APPROVED** [review]
all good

**Review by CarolineRinks — APPROVED** [review]

**Review by robobenklein — CHANGES_REQUESTED** [review]
Still awaiting a choice or proposal of a project.

**Review by colepjohn — APPROVED** [review]

**Review by colepjohn — APPROVED** [review]

**Review by CarolineRinks — APPROVED** [review]

**Review by robobenklein — APPROVED** [review]
discussed project in email, sounds good

**Pull request merged**
