### PR TITLE
Added Team Info

### PR DESCRIPTION
**Pull request by joshoua**

### CODE REVIEW

**Comment by robobenklein** [comment]
When your team members get into the org make sure you assign them to this PR otherwise they won't be in the team!

**Comment by joshoua** [comment]
Zachary is already added to the students directory and McKenzie just made a pull request for her file too.

**Review by mward-23 — APPROVED** [review]

**Review by mdeleon7 — APPROVED** [review]

**Review by zhamm643 — APPROVED** [review]

**Comment by AZHenley** [comment]
I need a bit more description of the project. Is it a photo processing app like Lightroom? An example flow would be: open and view photo, apply various tweaks/filters, see a preview of the output, and then can apply that set of filters to an entire directory... is that correct?

**Review by AZHenley — CHANGES_REQUESTED** [review]
I need a bit more description of the project. Is it a photo processing app like Lightroom? An example flow would be: open and view photo, apply various tweaks/filters, see a preview of the output, and then can apply that set of filters to an entire directory... is that correct?

**Comment by joshoua** [comment]
Updated! : )

**Comment by AZHenley** [comment]
> Updated, but the md literally already said image processing application. 

That is vague.

> And since it is a graphical application I think it is pretty obvious that it will have a preview of the enhancements. 

No, it isn't obvious.

> Did you read the entire file? 

Yes, and it is lacking.

@joshoua Let me know when you're free to meet to discuss your inappropriate communication.

**Review by AZHenley — APPROVED** [review]

**Pull request merged**
