### PR TITLE
Create fxie6.md

### PR DESCRIPTION
**Pull request by Franklin-Xie**

### CODE REVIEW

**Comment by robobenklein** [comment]
Hi, just want to make sure you have your local git environment set up and working before I merge this! (Since you made that commit on github.)

Part of this process is to make sure that you have your local git and python environment ready to work on your projects.

**Comment by Franklin-Xie** [comment]
I tried to do it through a terminal, but when I try to use git push I get:
ERROR: Permission to utk-cs/CS340-Fall-2021.git denied to Franklin-Xie.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by robobenklein** [comment]
Were you one I talked to after class?

The reason that error occurred was because you had the utk-cs repo remote url instead of your fork's.

If all is solved now, let me know and I'll merge this!

**Comment by Franklin-Xie** [comment]
Yes, I was and yeah all is goodThanks again Sent from Mail for Windows From: Ben KleinSent: Tuesday, September 7, 2021 7:05 PMTo: utk-cs/CS340-Fall-2021Cc: Franklin_Xie; AuthorSubject: Re: [utk-cs/CS340-Fall-2021] Create fxie6.md (#31) Were you one I talked to after class?The reason that error occurred was because you had the utk-cs repo remote url instead of your fork's.If all is solved now, let me know and I'll merge this!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
