### PR TITLE
Addteam

### PR DESCRIPTION
**Pull request by NehPatel2000**
please let me know if this is wrong, sorry for the mess-ups

## Contributors
 * Neh Patel
     * netid: npatel79
     * Github username: napatel79

 * Nima Tayefeh
     * netid: ntayefeh
     * Github username: NimsTay

 * Kyung Min Han 
     * netid: kyumhan 
     * Github username: kyumhan

 * Christopher Lee 
     * netid: clee95 
     * Github username: cjlee95

 * Joonyoung Im 
     * netid: jim5 
     * github username: troy51538

### CODE REVIEW

**Review by kyumhan — APPROVED** [review]

**Review by NimsTay — APPROVED** [review]

**Review by troy51538 — APPROVED** [review]
approve

**Review by cjlee95 — APPROVED** [review]

**Comment by robobenklein** [comment]
Cool, if you can please make it a markdown file (`.md`)

Any project ideas? (Preferred example even?)

**Review by NehPatel2000 — COMMENTED** [review]
changed to .md

**Comment by NehPatel2000** [comment]
@robobenklein is it good now? we are thinking about making a 2 player 2d shooting game which spawns players in a maze.

**Comment by robobenklein** [comment]
Awesome, I like the idea, try to explain / describe it in your team's file.

Don't worry about getting this PR merged before thursday, only the personal/student PRs are due tomorrow, we'll be going over team assignments on the weekend most likely when we have it all automated.

**Comment by NehPatel2000** [comment]
Thanks

**Review by kyumhan — APPROVED** [review]

**Comment by NehPatel2000** [comment]
@robobenklein hello, we added our proposal, what is the next step?

**Comment by robobenklein** [comment]
I've used both PyGame and Qt, but never together, how do you propose that will work, since they're both designed to serve a similar component? (They both render interactive views / UIs, just with different goals)

Also is pvp local or networked? Could you elaborate on how controls would work or how the network component would be structured?

**Comment by NehPatel2000** [comment]
@robobenklein  we were thinking of using pygame for the physics while we would use Qt for the ui. the game will be local and played on the same computer ie one player uses wasd to move and another uses arrow keys

**Review by robobenklein — APPROVED** [review]

**Comment by robobenklein** [comment]
@AZHenley your approval merges

**Review by robobenklein — APPROVED** [review]
I don't feel like waiting for henley's approval lol

**Pull request merged**
