### PR TITLE
Added Team file.

### PR DESCRIPTION
**Pull request by bparke37**

### CODE REVIEW

**Comment by robobenklein** [comment]
should rm that space from the filename

**Comment by gcrois** [comment]
> 
> 
> should rm that space from the filename

This is blatant prejudice against teams with whitespace in their names. We urge you to reconsider your words.

Also, why does this have the missing-members label?

**Comment by robobenklein** [comment]
@CadeBrown missing from assignees

**Comment by robobenklein** [comment]
blame GitHub for not allowing whitespace in repos or team names

**Comment by bparke37** [comment]
It's actually a brail blank character so technically not whitespace. Will remove anyway though if you don't want it.

**Comment by robobenklein** [comment]
the team name has to be usable in the name of a github repo, so that's probably the most restrictive requirement on it

**Comment by bparke37** [comment]
Sadly braille blank does not work in repo names. Will submit a fix soon.

**Comment by bparke37** [comment]
The team name has been renamed to `relevant_`  which is allowed as a repo name.

**Review by robobenklein — APPROVED** [review]

**Review by AZHenley — APPROVED** [review]

**Comment by AZHenley** [comment]
Spoke to them Thursday about this project. Sounds good to me.

**Pull request merged**
