### PR TITLE
Team Plumed

### PR DESCRIPTION
**Pull request by robobenklein**
This is a PR for a randomly selected team, you all are required to pull the branch it's on, add your team file matching the name of this branch (`plumed.md`) and fill it with your member list and project choice.

### CODE REVIEW

**Comment by robobenklein** [comment]
pending @jmuncy2 (need to accept org invite & assign to this PR)

**Comment by robobenklein** [comment]
Heads up: this being *merged* (requiring review and approval by us) is due by class time. @jmuncy2 @BGull00 can take some more time if needed, but everyone else who hasn't informed us of special circumstances ahead of time will receive a zero.

**Comment by jmuncy2** [comment]
i am confused by what you mean that you're waiting on me. what else do i need to do?

**Comment by jmuncy2** [comment]
I'm open to doing any of the projects if anyone has any preferences

**Review by jAllieB — APPROVED** [review]
Looks good?

**Review by ahillhou — APPROVED** [review]
I approve

**Review by BGull00 — APPROVED** [review]

**Review by tristan-ainley — APPROVED** [review]

**Comment by BGull00** [comment]
Added plumed.md team file and all Reviewers have approved

**Comment by BGull00** [comment]
When do we get our repo? If it's already been created, where can we find it? @robobenklein or @solsane

**Comment by robobenklein** [comment]
https://github.com/utk-cs/plumed

**Pull request merged**
