### PR TITLE
add my student file

### PR DESCRIPTION
**Pull request by marydenise**

### CODE REVIEW

**Comment by robobenklein** [comment]
You'll need to make sure that your local git config is correct before this can be accepted!

Make sure the email you're committing with is verified on your github account!

**Comment by marydenise** [comment]
How do I fix this?

**Comment by robobenklein** [comment]
Follow the instructions at https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

**Comment by marydenise** [comment]
Let me know if it’s good now, fixed the email in git

**Comment by robobenklein** [comment]
Make sure you push a commit here that shows you have it linked properly, it can be as simple as adding a new line or you can just make an empty commit.

**Comment by marydenise** [comment]
Got it

**Pull request merged**
