### PR TITLE
Team Mallard

### PR DESCRIPTION
**Pull request by robobenklein**
This is a PR for a randomly selected team, you all are required to pull the branch it's on, add your team file matching the name of this branch (`mallard.md`) and fill it with your member list and project choice.

### CODE REVIEW

**Comment by argvrutter** [comment]
pending accept: wiihop69

**Review by LouLoog — COMMENTED** [review]
Question: What am I suppose to be reviewing here??? Also, I tried pushing a mallard.md into /team and I couldn't cause it was protected.

**Comment by robobenklein** [comment]
@LouLoog make sure you checkout / switch to the branch for this PR and make the change there. (P.S. you can do what's called a "cherry pick" of a commit to copy those changes from one branch to another)

**Comment by LouLoog** [comment]
96d5eddd339a462ef674715435339d180c8138e4 Did I do it right???

**Comment by robobenklein** [comment]
Indeed, if none of the group have a project to propose, do the weather app.

**Pull request merged**
